### PR TITLE
fix a normURL bug

### PR DESCRIPTION
**Pull request by mzch**
fixed a bug about error handling of normURL

### CODE REVIEW

**Comment by popey456963** [comment]
Hello, this takes out any checking of the redirect URL.  Whilst it will make it function, it will also allow _anything_ through.

**Comment by mzch** [comment]
Well, in the original I put `https://upldr.info/login_callback` into redirect URL, but this check never passes.
```
https://auth.upldr.info/api/auth?id=[ConsumerID]&redirect=https://upldr.info/login_callback%3Fto=%3Dhttps%3A%2F%2Fupldr.info%2F
```
Another issue?

**Comment by mzch** [comment]
In this time,
redirects =`["https://upldr.info/login_callback"]`
origUrl = `https://upldr.info`
but IndexOf() returns -1
Perhaps blanket in redirects needs to be stripped.

**Comment by mzch** [comment]
And one more problem, `normURL()` strips `/login_callback`. it lacks the precision to comparing request param and registered reidrect URL.

Sugegestion:
```diff
--- foreign.js.orig	2020-09-17 10:44:20.096812562 -0700
+++ foreign.js	2020-09-17 10:41:48.256497013 -0700
@@ -26,15 +26,8 @@
     }

     let redirects = consumer.redirects
-    let url
-    try {
-        url = new URL(redirect)
-    } catch(e) {
-        return res.json({ err: 'Cannot Parse Redirect URL' })
-    }

-    let origUrl = normUrl(url.origin)
-    if (redirects.indexOf(origUrl) == -1) {
+    if (redirects.indexOf(reidrect) == -1) {
         return res.json({ err: 'Unacceptable Redirect' })
     }
```

**Comment by mzch** [comment]
This code is passed and compares URL include URL.pathname.
How about?

```diff
--- foreign.js.orig	2020-09-17 10:44:20.096812562 -0700
+++ foreign.js	2020-09-17 11:11:22.063154228 -0700
@@ -26,15 +26,21 @@
     }

     let redirects = consumer.redirects
+
     let url
     try {
-        url = new URL(redirect)
+        url = new URL(redirects)
     } catch(e) {
         return res.json({ err: 'Cannot Parse Redirect URL' })
     }
-
-    let origUrl = normUrl(url.origin)
-    if (redirects.indexOf(origUrl) == -1) {
+
+    let callbackUrl = url.origin
+    if (callbackUrl.port) {
+        callbackUrl += ":" + port
+    }
+    callbackUrl += url.pathname
+
+    if (redirect.indexOf(callbackUrl) == -1) {
         return res.json({ err: 'Unacceptable Redirect' })
     }
```

**Comment by mzch** [comment]
I'm going to close this PR and recreate new one.

**Pull request closed without merging**
